-- MySQL Script generated by MySQL Workbench
-- dom 10 oct 2021 17:24:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_store` DEFAULT CHARACTER SET utf8 ;
USE `online_store` ;

-- -----------------------------------------------------
-- Table `online_store`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store`.`Customers` (
  `Username` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `PostalCode` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store`.`Users` (
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(250) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Picture` VARCHAR(45) NULL,
  `Customers_Username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Username`),
  INDEX `fk_Users_Customers_idx` (`Customers_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Customers`
    FOREIGN KEY (`Customers_Username`)
    REFERENCES `online_store`.`Customers` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store`.`Orders` (
  `OrderNumber` INT NOT NULL,
  `Date` DATE NULL,
  `Status` TINYINT NULL,
  `TrackingNumber` VARCHAR(45) NULL,
  `Total` FLOAT NULL,
  `Customers_Username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OrderNumber`),
  INDEX `fk_Orders_Customers1_idx` (`Customers_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`Customers_Username`)
    REFERENCES `online_store`.`Customers` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store`.`Categories` (
  `CategorieId` INT NOT NULL,
  `CategorieName` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`CategorieId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store`.`Products` (
  `ProductCode` INT NOT NULL,
  `ProductName` VARCHAR(45) NULL,
  `Description` VARCHAR(145) NULL,
  `Price` FLOAT NULL,
  `ProductAvailable` INT NULL,
  `Picture` VARCHAR(45) NULL,
  `Brand` VARCHAR(45) NULL,
  `Model` VARCHAR(45) NULL,
  `Year` YEAR NULL,
  `Categories_CategorieId` INT NOT NULL,
  PRIMARY KEY (`ProductCode`),
  INDEX `fk_Products_Categories1_idx` (`Categories_CategorieId` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`Categories_CategorieId`)
    REFERENCES `online_store`.`Categories` (`CategorieId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store`.`OrderDetails` (
  `Products_ProductCode` INT NOT NULL,
  `Orders_OrderNumber` INT NOT NULL,
  `OrderDetail_id` INT NOT NULL,
  PRIMARY KEY (`Products_ProductCode`, `Orders_OrderNumber`, `OrderDetail_id`),
  INDEX `fk_Products_has_Orders_Orders1_idx` (`Orders_OrderNumber` ASC) VISIBLE,
  INDEX `fk_Products_has_Orders_Products1_idx` (`Products_ProductCode` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Orders_Products1`
    FOREIGN KEY (`Products_ProductCode`)
    REFERENCES `online_store`.`Products` (`ProductCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Orders_Orders1`
    FOREIGN KEY (`Orders_OrderNumber`)
    REFERENCES `online_store`.`Orders` (`OrderNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
