version: "3.1"
services:
  mysql2:
    image: mysql:latest
    container_name: mysql2
    environment:
      - MYSQL_DATABASE=online_store
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
    ports:
      - "3336:3306"

  webserver:
    image: tomcat:alpine
    container_name: tomcat
    volumes:
     - ./tomcat/prueba2.war:/usr/local/tomcat/webapps/prueba2.war
    ports:
      - "9091:8080"

