version: "3.1"
services:
  mysql2:
    image: mysql:latest
    container_name: mysql2
    environment:
      - MYSQL_DATABASE=online_store
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
     # - MYSQL_ROOT_HOST='%'
     # - MYSQL_USER=david
     # - MYSQL_PASSWORD=david
    ports:
      - "3336:3306"

  webserver:
    image: tomcat:jdk11-slim
    container_name: tomcat
    volumes:
     - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
     - ./tomcat/context.xml:/usr/local/tomcat/conf/Catalina/localhost/manager.xml:ro
     - ./tomcat/context.xml:/usr/local/tomcat/conf/Catalina/localhost/host-manager.xml:ro
    #  - ./tomcat/RestServerCarLicense.war:/usr/local/tomcat/webapps/RestServerCarLicense.war
    #  - ./tomcat/spring-starter-project.war:/usr/local/tomcat/webapps/spring-starter-project.war
     - ./tomcat/dawProject.war:/usr/local/tomcat/webapps/dawProject.war
     - ./tomcat/proyecto2.war:/usr/local/tomcat/webapps/proyecto2.war
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql2:3306/online_store?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      
    depends_on:
      - mysql2
    ports:
      - "9095:8080"

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mysql2
